// Ninja Bear Studio Inc., all rights reserved.
#include "NinjaInventoryGameplayTags.h"

UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Container_Lootable, "Inventory.Container.Lootable");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_Animation, "Inventory.Event.Animation");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_Animation_Activate, "Inventory.Event.Animation.Activate");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_Animation_Deactivate, "Inventory.Event.Animation.Deactivate");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_ChangedState, "Inventory.Event.ChangedState");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_ConsumeItem, "Inventory.Event.ConsumeItem");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_Equipment_Activate, "Inventory.Event.Equipment.Activate");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_Equipment_Deactivate, "Inventory.Event.Equipment.Deactivate");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_GenerateLoot, "Inventory.Event.GenerateLoot");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_ItemAdded, "Inventory.Event.ItemAdded");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_ItemRemoved, "Inventory.Event.ItemRemoved");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Event_ReceiveLoot, "Inventory.Event.ReceiveLoot");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Data_Durability, "Inventory.Item.Data.Durability");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Data_Weight, "Inventory.Item.Data.Weight");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Activate, "Inventory.Item.Fragment.Activate");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Combine, "Inventory.Item.Fragment.Combine");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Consume, "Inventory.Item.Fragment.Consume");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Deactivate, "Inventory.Item.Fragment.Deactivate");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Drop, "Inventory.Item.Fragment.Drop");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Move, "Inventory.Item.Fragment.Move");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Repair, "Inventory.Item.Fragment.Repair");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Split, "Inventory.Item.Fragment.Split");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Swap, "Inventory.Item.Fragment.Swap");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Transfer, "Inventory.Item.Fragment.Transfer");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Upgrade, "Inventory.Item.Fragment.Upgrade");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Operation_Wear, "Inventory.Item.Fragment.Wear");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Quality, "Inventory.Item.Quality");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Quality_Common, "Inventory.Item.Quality.Common");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Trait_Broken, "Inventory.Item.Trait.Broken");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Trait_Consumable, "Inventory.Item.Trait.Consumable");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Trait_Droppable, "Inventory.Item.Trait.Droppable");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Trait_Indestructible, "Inventory.Item.Trait.Indestructible");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Trait_Lootable, "Inventory.Item.Trait.Lootable");
UE_DEFINE_GAMEPLAY_TAG(Tag_Inventory_Item_Trait_Upgradeable, "Inventory.Item.Trait.Upgradeable");